# Generated by Django 5.2.5 on 2025-09-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('categoria', models.CharField(choices=[('doces', 'Doces'), ('salgados', 'Salgados'), ('bebidas', 'Bebidas'), ('sobremesas', 'Sobremesas')], default='salgados', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='receitas/img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-created_at'],
            },
        ),
    ]
