# Generated by Django 5.2.5 on 2025-09-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('doces', 'Doces'), ('salgados', 'Salgados'), ('bebidas', 'Bebidas'), ('sobremesas', 'Sobremesas')], default='salgados', max_length=20),
        ),
    ]
